"""
AI Recommendation Model
Stores AI trade recommendations for performance analytics and ML training
"""

from sqlalchemy import Column, String, Integer, Float, DateTime, Boolean, Text, Index
from sqlalchemy.sql import func
from app.config.database import Base


class AIRecommendation(Base):
    """
    AI Trade Recommendation tracking for performance analytics
    
    Stores every recommendation generated by the AI system with entry/exit
    details and outcomes for backtesting and strategy evaluation.
    """
    
    __tablename__ = "ai_recommendations"
    
    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Recommendation details
    symbol = Column(String(20), nullable=False, index=True)
    mode = Column(String(50), nullable=False, index=True)
    universe = Column(String(50), nullable=False)
    source = Column(String(100), nullable=False)
    recommendation = Column(String(50), nullable=False)
    direction = Column(String(10), nullable=False)
    
    # Timestamps
    generated_at_utc = Column(DateTime(timezone=True), nullable=False, index=True)
    
    # Entry details
    entry_price = Column(Float, nullable=True)
    stop_loss_price = Column(Float, nullable=True)
    target_price = Column(Float, nullable=True)
    
    # Scoring
    score_blend = Column(Float, nullable=True)
    confidence = Column(String(20), nullable=True)
    risk_profile = Column(String(50), nullable=True)
    
    # Run tracking
    run_id = Column(String(100), nullable=True, index=True)
    rank_in_run = Column(Integer, nullable=True)
    policy_version = Column(String(100), nullable=True)
    
    # Features (JSON stored as text)
    features_json = Column(Text, nullable=True)
    
    # Evaluation status
    evaluated = Column(Boolean, default=False, nullable=False, index=True)
    evaluated_at_utc = Column(DateTime(timezone=True), nullable=True)
    
    # Exit details
    exit_price = Column(Float, nullable=True)
    exit_time_utc = Column(DateTime(timezone=True), nullable=True)
    exit_reason = Column(String(100), nullable=True)
    
    # Performance metrics
    pnl_pct = Column(Float, nullable=True)
    max_drawdown_pct = Column(Float, nullable=True)
    alpha_vs_benchmark = Column(Float, nullable=True)
    
    # Labels (JSON stored as text)
    labels_json = Column(Text, nullable=True)
    
    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    
    # Indexes for common queries
    __table_args__ = (
        Index('idx_ai_rec_symbol_mode_time', 'symbol', 'mode', 'generated_at_utc'),
        Index('idx_ai_rec_evaluated_time', 'evaluated', 'generated_at_utc'),
        Index('idx_ai_rec_run_id', 'run_id'),
        Index('idx_ai_rec_source', 'source'),
    )
    
    def to_dict(self):
        """Convert model to dictionary"""
        return {
            "id": self.id,
            "symbol": self.symbol,
            "mode": self.mode,
            "universe": self.universe,
            "source": self.source,
            "recommendation": self.recommendation,
            "direction": self.direction,
            "generated_at_utc": self.generated_at_utc.isoformat() if self.generated_at_utc else None,
            "entry_price": self.entry_price,
            "stop_loss_price": self.stop_loss_price,
            "target_price": self.target_price,
            "score_blend": self.score_blend,
            "confidence": self.confidence,
            "risk_profile": self.risk_profile,
            "run_id": self.run_id,
            "rank_in_run": self.rank_in_run,
            "policy_version": self.policy_version,
            "evaluated": self.evaluated,
            "evaluated_at_utc": self.evaluated_at_utc.isoformat() if self.evaluated_at_utc else None,
            "exit_price": self.exit_price,
            "exit_time_utc": self.exit_time_utc.isoformat() if self.exit_time_utc else None,
            "exit_reason": self.exit_reason,
            "pnl_pct": self.pnl_pct,
            "max_drawdown_pct": self.max_drawdown_pct,
            "alpha_vs_benchmark": self.alpha_vs_benchmark,
        }
    
    def __repr__(self):
        return f"<AIRecommendation(id={self.id}, symbol={self.symbol}, mode={self.mode}, recommendation={self.recommendation})>"
